### ISSUE TITLE
Add menu item with shortcut to close editor tabs

### ISSUE THREAD

**Issue by wjk** [DotPurpleApp/DotPurple-App#2]
What the title says. By "editor" tabs I mean the tab for the screen that contains the details for a specific solution or csproj file (on the right side, at the top). If there are no "editor" tabs, you can simply do nothing. (Disabling the menu item in this situation is polite, but not technically required).

The Mac keyboard shortcut for this command should be ⌘W, because this is standard practice on macOS. (⌘ is called the Command key.) On Windows and Linux I would recommend using Ctrl+W instead.

BTW: You have an amazing product here (and one new customer)!

**Comment by Deadpikle** [comment]
@wjk Hi again! This is another great suggestion and one that will help devs not pull their hair out so much. 😝 

This will be available on all platforms when the new version is released -- probably within a few days (based on my schedule). Both the keyboard shortcut and menu option are there. I didn't do the disabling of the menu item since time is limited right now and that's a bit more complex with our internal code structure, but most will use the keyboard shortcut anyway.

Will close when the new version is deployed.

> BTW: You have an amazing product here (and one new customer)!

Thank you! :) Please spread the word about DotPurple! :)

**Comment by Deadpikle** [comment]
Closing as this feature as now been released.
