### ISSUE TITLE
[Bug] problem with russian encodings

### ISSUE THREAD

**Issue by zverev-iv** [DotPurpleApp/DotPurple-App#5]
**Describe the bug**
if I run command 

```dotnet build some.csproj``` in terminal I see:
```
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Определение проектов для восстановления...
  Все проекты обновлены для восстановления.
```

if i run the same in DotPurple I see

```
Microsoft (R) Build Engine ўҐабЁЁ 16.9.0+57a23d249 ¤«п .NET
(C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation). ‚бҐ Їа ў  § йЁйҐ­л.

  ЋЇаҐ¤Ґ«Ґ­ЁҐ Їа®ҐЄв®ў ¤«п ў®ббв ­®ў«Ґ­Ёп...
  ‚бҐ Їа®ҐЄвл ®Ў­®ў«Ґ­л ¤«п ў®ббв ­®ў«Ґ­Ёп.
```

so we have problem with terminal encoding in dotpurple.
default codepage in terminal on my system (default if russian is default system language in windows) is 866.
If I change codepage in terminal  to 65001 (before build start) it also works.

**To Reproduce**
1. Set Russian Language as default in system
2. run build of csproject

**Expected behavior**
I need text in terminal in correct encoding

**Desktop (please complete the following information):**
 - OS: Windows 10 (Version 10.0.19042.867)
 - Version 1.5.2.0

**Comment by Deadpikle** [comment]
Hi @zverev-iv,

Thanks for the bug report!

This might be due to a difference in system language versus DotPurple forcing all console output to be in English (for technical reasons). We have very limited internationalization support.

We've made some attempts to fix this issue -- all DotPurple console output should now be in code page 65001. (Thanks for that tip.)

Can you give build 1.5.3.0 on Windows a try and let us know if it fixes the issue for you, please? You can use the built-in software updater or download it from our website. Thanks! 😄

**Comment by zverev-iv** [comment]
Works properly in 1.5.3.0, thanks a lot!
